server:
  port: 8080
  
spring:
  application:
    name: simple-service
  cloud:
    config:
      profile: ${config.profile:debug}
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/