spring:
  application:
    name: simple-service
  cloud:
    config:
      profile: ${config.profile:debug}
      name: simple-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/