spring:
  application:
    name: eureka-server
      
server:
  port: 8761
  
eureka:
  instance:
    hostname:localhost
  server:
    peerip:localhost
    peerport:8762
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.peerip}:${eureka.server.peerport}/eureka/
