server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      profile: ${config.profile:debug}
      server:
        git:
          uri: https://github.com/yingkongshi/spring-cloud-netflix-demo.git
          search-paths: cloud-config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
